// <auto-generated>
namespace Plover.Dom
{
    /// <summary>
    /// Class representing the 'body' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Body : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Body"/> class.
        /// </summary>
        public Body()
            : base("body")
        {
        }
    }

    /// <summary>
    /// Class representing the 'address' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Address : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Address"/> class.
        /// </summary>
        public Address()
            : base("address")
        {
        }
    }

    /// <summary>
    /// Class representing the 'article' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Article : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Article"/> class.
        /// </summary>
        public Article()
            : base("article")
        {
        }
    }

    /// <summary>
    /// Class representing the 'aside' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Aside : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Aside"/> class.
        /// </summary>
        public Aside()
            : base("aside")
        {
        }
    }

    /// <summary>
    /// Class representing the 'footer' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Footer : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Footer"/> class.
        /// </summary>
        public Footer()
            : base("footer")
        {
        }
    }

    /// <summary>
    /// Class representing the 'header' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Header : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Header"/> class.
        /// </summary>
        public Header()
            : base("header")
        {
        }
    }

    /// <summary>
    /// Class representing the 'h1' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Heading1 : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Heading1"/> class.
        /// </summary>
        public Heading1()
            : base("h1")
        {
        }
    }

    /// <summary>
    /// Class representing the 'h2' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Heading2 : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Heading2"/> class.
        /// </summary>
        public Heading2()
            : base("h2")
        {
        }
    }

    /// <summary>
    /// Class representing the 'h3' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Heading3 : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Heading3"/> class.
        /// </summary>
        public Heading3()
            : base("h3")
        {
        }
    }

    /// <summary>
    /// Class representing the 'h4' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Heading4 : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Heading4"/> class.
        /// </summary>
        public Heading4()
            : base("h4")
        {
        }
    }

    /// <summary>
    /// Class representing the 'h5' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Heading5 : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Heading5"/> class.
        /// </summary>
        public Heading5()
            : base("h5")
        {
        }
    }

    /// <summary>
    /// Class representing the 'h6' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Heading6 : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Heading6"/> class.
        /// </summary>
        public Heading6()
            : base("h6")
        {
        }
    }

    /// <summary>
    /// Class representing the 'hgroup' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class HeadingGroup : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HeadingGroup"/> class.
        /// </summary>
        public HeadingGroup()
            : base("hgroup")
        {
        }
    }

    /// <summary>
    /// Class representing the 'main' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Main : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Main"/> class.
        /// </summary>
        public Main()
            : base("main")
        {
        }
    }

    /// <summary>
    /// Class representing the 'nav' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Navigation : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Navigation"/> class.
        /// </summary>
        public Navigation()
            : base("nav")
        {
        }
    }

    /// <summary>
    /// Class representing the 'section' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Section : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Section"/> class.
        /// </summary>
        public Section()
            : base("section")
        {
        }
    }

    /// <summary>
    /// Class representing the 'blockquote' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class BlockQuote : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BlockQuote"/> class.
        /// </summary>
        public BlockQuote()
            : base("blockquote")
        {
        }
    }

    /// <summary>
    /// Class representing the 'dd' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Description : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Description"/> class.
        /// </summary>
        public Description()
            : base("dd")
        {
        }
    }

    /// <summary>
    /// Class representing the 'dir' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Directory : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Directory"/> class.
        /// </summary>
        public Directory()
            : base("dir")
        {
        }
    }

    /// <summary>
    /// Class representing the 'div' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Division : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Division"/> class.
        /// </summary>
        public Division()
            : base("div")
        {
        }
    }

    /// <summary>
    /// Class representing the 'dl' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class DescriptionList : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DescriptionList"/> class.
        /// </summary>
        public DescriptionList()
            : base("dl")
        {
        }
    }

    /// <summary>
    /// Class representing the 'dt' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class DescriptionTerm : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DescriptionTerm"/> class.
        /// </summary>
        public DescriptionTerm()
            : base("dt")
        {
        }
    }

    /// <summary>
    /// Class representing the 'figcaption' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class FigureCaption : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FigureCaption"/> class.
        /// </summary>
        public FigureCaption()
            : base("figcaption")
        {
        }
    }

    /// <summary>
    /// Class representing the 'figure' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Figure : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Figure"/> class.
        /// </summary>
        public Figure()
            : base("figure")
        {
        }
    }

    /// <summary>
    /// Class representing the 'hr' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class ThematicBreak : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ThematicBreak"/> class.
        /// </summary>
        public ThematicBreak()
            : base("hr")
        {
        }
    }

    /// <summary>
    /// Class representing the 'li' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class ListItem : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ListItem"/> class.
        /// </summary>
        public ListItem()
            : base("li")
        {
        }
    }

    /// <summary>
    /// Class representing the 'ol' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class OrderedList : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OrderedList"/> class.
        /// </summary>
        public OrderedList()
            : base("ol")
        {
        }
    }

    /// <summary>
    /// Class representing the 'p' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Paragraph : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Paragraph"/> class.
        /// </summary>
        public Paragraph()
            : base("p")
        {
        }
    }

    /// <summary>
    /// Class representing the 'pre' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Preformatted : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Preformatted"/> class.
        /// </summary>
        public Preformatted()
            : base("pre")
        {
        }
    }

    /// <summary>
    /// Class representing the 'ul' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class UnorderedList : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UnorderedList"/> class.
        /// </summary>
        public UnorderedList()
            : base("ul")
        {
        }
    }

    /// <summary>
    /// Class representing the 'a' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Anchor : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Anchor"/> class.
        /// </summary>
        public Anchor()
            : base("a")
        {
        }
    }

    /// <summary>
    /// Class representing the 'abbr' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Abbreviation : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Abbreviation"/> class.
        /// </summary>
        public Abbreviation()
            : base("abbr")
        {
        }
    }

    /// <summary>
    /// Class representing the 'b' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Bold : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Bold"/> class.
        /// </summary>
        public Bold()
            : base("b")
        {
        }
    }

    /// <summary>
    /// Class representing the 'bdi' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class BidirectionalIsolate : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BidirectionalIsolate"/> class.
        /// </summary>
        public BidirectionalIsolate()
            : base("bdi")
        {
        }
    }

    /// <summary>
    /// Class representing the 'bdo' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class BidirectionalOverride : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BidirectionalOverride"/> class.
        /// </summary>
        public BidirectionalOverride()
            : base("bdo")
        {
        }
    }

    /// <summary>
    /// Class representing the 'br' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Break : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Break"/> class.
        /// </summary>
        public Break()
            : base("br")
        {
        }
    }

    /// <summary>
    /// Class representing the 'cite' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Cite : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Cite"/> class.
        /// </summary>
        public Cite()
            : base("cite")
        {
        }
    }

    /// <summary>
    /// Class representing the 'code' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Code : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Code"/> class.
        /// </summary>
        public Code()
            : base("code")
        {
        }
    }

    /// <summary>
    /// Class representing the 'data' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Data : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Data"/> class.
        /// </summary>
        public Data()
            : base("data")
        {
        }
    }

    /// <summary>
    /// Class representing the 'dfn' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Definition : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Definition"/> class.
        /// </summary>
        public Definition()
            : base("dfn")
        {
        }
    }

    /// <summary>
    /// Class representing the 'em' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Emphasis : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Emphasis"/> class.
        /// </summary>
        public Emphasis()
            : base("em")
        {
        }
    }

    /// <summary>
    /// Class representing the 'i' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Italic : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Italic"/> class.
        /// </summary>
        public Italic()
            : base("i")
        {
        }
    }

    /// <summary>
    /// Class representing the 'kbd' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class KeyboardInput : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="KeyboardInput"/> class.
        /// </summary>
        public KeyboardInput()
            : base("kbd")
        {
        }
    }

    /// <summary>
    /// Class representing the 'mark' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Mark : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Mark"/> class.
        /// </summary>
        public Mark()
            : base("mark")
        {
        }
    }

    /// <summary>
    /// Class representing the 'q' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Quotation : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Quotation"/> class.
        /// </summary>
        public Quotation()
            : base("q")
        {
        }
    }

    /// <summary>
    /// Class representing the 'rb' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class RubyBase : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RubyBase"/> class.
        /// </summary>
        public RubyBase()
            : base("rb")
        {
        }
    }

    /// <summary>
    /// Class representing the 'rp' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class RubyFallback : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RubyFallback"/> class.
        /// </summary>
        public RubyFallback()
            : base("rp")
        {
        }
    }

    /// <summary>
    /// Class representing the 'rt' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class RubyText : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RubyText"/> class.
        /// </summary>
        public RubyText()
            : base("rt")
        {
        }
    }

    /// <summary>
    /// Class representing the 'rtc' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class RubyTextContainer : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RubyTextContainer"/> class.
        /// </summary>
        public RubyTextContainer()
            : base("rtc")
        {
        }
    }

    /// <summary>
    /// Class representing the 'ruby' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Ruby : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Ruby"/> class.
        /// </summary>
        public Ruby()
            : base("ruby")
        {
        }
    }

    /// <summary>
    /// Class representing the 's' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Strikethrough : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Strikethrough"/> class.
        /// </summary>
        public Strikethrough()
            : base("s")
        {
        }
    }

    /// <summary>
    /// Class representing the 'samp' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Sample : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Sample"/> class.
        /// </summary>
        public Sample()
            : base("samp")
        {
        }
    }

    /// <summary>
    /// Class representing the 'small' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Small : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Small"/> class.
        /// </summary>
        public Small()
            : base("small")
        {
        }
    }

    /// <summary>
    /// Class representing the 'span' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Span : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Span"/> class.
        /// </summary>
        public Span()
            : base("span")
        {
        }
    }

    /// <summary>
    /// Class representing the 'strong' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Strong : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Strong"/> class.
        /// </summary>
        public Strong()
            : base("strong")
        {
        }
    }

    /// <summary>
    /// Class representing the 'sub' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Subscript : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Subscript"/> class.
        /// </summary>
        public Subscript()
            : base("sub")
        {
        }
    }

    /// <summary>
    /// Class representing the 'sup' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Superscript : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Superscript"/> class.
        /// </summary>
        public Superscript()
            : base("sup")
        {
        }
    }

    /// <summary>
    /// Class representing the 'time' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Time : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Time"/> class.
        /// </summary>
        public Time()
            : base("time")
        {
        }
    }

    /// <summary>
    /// Class representing the 'tt' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Teletype : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Teletype"/> class.
        /// </summary>
        public Teletype()
            : base("tt")
        {
        }
    }

    /// <summary>
    /// Class representing the 'u' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Unarticulated : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Unarticulated"/> class.
        /// </summary>
        public Unarticulated()
            : base("u")
        {
        }
    }

    /// <summary>
    /// Class representing the 'var' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Variable : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Variable"/> class.
        /// </summary>
        public Variable()
            : base("var")
        {
        }
    }

    /// <summary>
    /// Class representing the 'wbr' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class WordBreak : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WordBreak"/> class.
        /// </summary>
        public WordBreak()
            : base("wbr")
        {
        }
    }

    /// <summary>
    /// Class representing the 'area' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Area : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Area"/> class.
        /// </summary>
        public Area()
            : base("area")
        {
        }
    }

    /// <summary>
    /// Class representing the 'audio' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Audio : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Audio"/> class.
        /// </summary>
        public Audio()
            : base("audio")
        {
        }
    }

    /// <summary>
    /// Class representing the 'img' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Image : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Image"/> class.
        /// </summary>
        public Image()
            : base("img")
        {
        }
    }

    /// <summary>
    /// Class representing the 'map' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Map : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Map"/> class.
        /// </summary>
        public Map()
            : base("map")
        {
        }
    }

    /// <summary>
    /// Class representing the 'track' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Track : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Track"/> class.
        /// </summary>
        public Track()
            : base("track")
        {
        }
    }

    /// <summary>
    /// Class representing the 'video' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Video : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Video"/> class.
        /// </summary>
        public Video()
            : base("video")
        {
        }
    }

    /// <summary>
    /// Class representing the 'applet' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Applet : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Applet"/> class.
        /// </summary>
        public Applet()
            : base("applet")
        {
        }
    }

    /// <summary>
    /// Class representing the 'embed' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Embed : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Embed"/> class.
        /// </summary>
        public Embed()
            : base("embed")
        {
        }
    }

    /// <summary>
    /// Class representing the 'iframe' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Iframe : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Iframe"/> class.
        /// </summary>
        public Iframe()
            : base("iframe")
        {
        }
    }

    /// <summary>
    /// Class representing the 'object' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class ResourceObject : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ResourceObject"/> class.
        /// </summary>
        public ResourceObject()
            : base("object")
        {
        }
    }

    /// <summary>
    /// Class representing the 'param' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class ObjectParameter : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ObjectParameter"/> class.
        /// </summary>
        public ObjectParameter()
            : base("param")
        {
        }
    }

    /// <summary>
    /// Class representing the 'picture' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Picture : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Picture"/> class.
        /// </summary>
        public Picture()
            : base("picture")
        {
        }
    }

    /// <summary>
    /// Class representing the 'source' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Source : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Source"/> class.
        /// </summary>
        public Source()
            : base("source")
        {
        }
    }

    /// <summary>
    /// Class representing the 'canvas' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Canvas : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Canvas"/> class.
        /// </summary>
        public Canvas()
            : base("canvas")
        {
        }
    }

    /// <summary>
    /// Class representing the 'noscript' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Noscript : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Noscript"/> class.
        /// </summary>
        public Noscript()
            : base("noscript")
        {
        }
    }

    /// <summary>
    /// Class representing the 'script' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Script : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Script"/> class.
        /// </summary>
        public Script()
            : base("script")
        {
        }
    }

    /// <summary>
    /// Class representing the 'del' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Deleted : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Deleted"/> class.
        /// </summary>
        public Deleted()
            : base("del")
        {
        }
    }

    /// <summary>
    /// Class representing the 'ins' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Inserted : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Inserted"/> class.
        /// </summary>
        public Inserted()
            : base("ins")
        {
        }
    }

    /// <summary>
    /// Class representing the 'caption' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Caption : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Caption"/> class.
        /// </summary>
        public Caption()
            : base("caption")
        {
        }
    }

    /// <summary>
    /// Class representing the 'col' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Column : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Column"/> class.
        /// </summary>
        public Column()
            : base("col")
        {
        }
    }

    /// <summary>
    /// Class representing the 'colgroup' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class ColumnGroup : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ColumnGroup"/> class.
        /// </summary>
        public ColumnGroup()
            : base("colgroup")
        {
        }
    }

    /// <summary>
    /// Class representing the 'table' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Table : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Table"/> class.
        /// </summary>
        public Table()
            : base("table")
        {
        }
    }

    /// <summary>
    /// Class representing the 'tbody' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class TableBody : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TableBody"/> class.
        /// </summary>
        public TableBody()
            : base("tbody")
        {
        }
    }

    /// <summary>
    /// Class representing the 'td' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class TableData : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TableData"/> class.
        /// </summary>
        public TableData()
            : base("td")
        {
        }
    }

    /// <summary>
    /// Class representing the 'tfoot' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class TableFooter : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TableFooter"/> class.
        /// </summary>
        public TableFooter()
            : base("tfoot")
        {
        }
    }

    /// <summary>
    /// Class representing the 'th' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class TablerHeader : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TablerHeader"/> class.
        /// </summary>
        public TablerHeader()
            : base("th")
        {
        }
    }

    /// <summary>
    /// Class representing the 'thead' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class TableHeaders : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TableHeaders"/> class.
        /// </summary>
        public TableHeaders()
            : base("thead")
        {
        }
    }

    /// <summary>
    /// Class representing the 'tr' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class TableRow : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TableRow"/> class.
        /// </summary>
        public TableRow()
            : base("tr")
        {
        }
    }

    /// <summary>
    /// Class representing the 'button' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Button : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Button"/> class.
        /// </summary>
        public Button()
            : base("button")
        {
        }
    }

    /// <summary>
    /// Class representing the 'datalist' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class DataList : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DataList"/> class.
        /// </summary>
        public DataList()
            : base("datalist")
        {
        }
    }

    /// <summary>
    /// Class representing the 'fieldset' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class FieldSet : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FieldSet"/> class.
        /// </summary>
        public FieldSet()
            : base("fieldset")
        {
        }
    }

    /// <summary>
    /// Class representing the 'form' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Form : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Form"/> class.
        /// </summary>
        public Form()
            : base("form")
        {
        }
    }

    /// <summary>
    /// Class representing the 'input' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Input : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Input"/> class.
        /// </summary>
        public Input()
            : base("input")
        {
        }
    }

    /// <summary>
    /// Class representing the 'label' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Label : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Label"/> class.
        /// </summary>
        public Label()
            : base("label")
        {
        }
    }

    /// <summary>
    /// Class representing the 'legend' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Legend : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Legend"/> class.
        /// </summary>
        public Legend()
            : base("legend")
        {
        }
    }

    /// <summary>
    /// Class representing the 'meter' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Meter : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Meter"/> class.
        /// </summary>
        public Meter()
            : base("meter")
        {
        }
    }

    /// <summary>
    /// Class representing the 'optgroup' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class OptionGroup : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OptionGroup"/> class.
        /// </summary>
        public OptionGroup()
            : base("optgroup")
        {
        }
    }

    /// <summary>
    /// Class representing the 'option' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Option : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Option"/> class.
        /// </summary>
        public Option()
            : base("option")
        {
        }
    }

    /// <summary>
    /// Class representing the 'output' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Output : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Output"/> class.
        /// </summary>
        public Output()
            : base("output")
        {
        }
    }

    /// <summary>
    /// Class representing the 'progress' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Progress : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Progress"/> class.
        /// </summary>
        public Progress()
            : base("progress")
        {
        }
    }

    /// <summary>
    /// Class representing the 'select' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Select : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Select"/> class.
        /// </summary>
        public Select()
            : base("select")
        {
        }
    }

    /// <summary>
    /// Class representing the 'textarea' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class TextArea : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TextArea"/> class.
        /// </summary>
        public TextArea()
            : base("textarea")
        {
        }
    }

    /// <summary>
    /// Class representing the 'details' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Details : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Details"/> class.
        /// </summary>
        public Details()
            : base("details")
        {
        }
    }

    /// <summary>
    /// Class representing the 'dialog' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Dialog : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Dialog"/> class.
        /// </summary>
        public Dialog()
            : base("dialog")
        {
        }
    }

    /// <summary>
    /// Class representing the 'menu' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Menu : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Menu"/> class.
        /// </summary>
        public Menu()
            : base("menu")
        {
        }
    }

    /// <summary>
    /// Class representing the 'menuitem' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class MenuItem : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MenuItem"/> class.
        /// </summary>
        public MenuItem()
            : base("menuitem")
        {
        }
    }

    /// <summary>
    /// Class representing the 'summary' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Summary : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Summary"/> class.
        /// </summary>
        public Summary()
            : base("summary")
        {
        }
    }

    /// <summary>
    /// Class representing the 'content' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Content : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Content"/> class.
        /// </summary>
        public Content()
            : base("content")
        {
        }
    }

    /// <summary>
    /// Class representing the 'element' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Element : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Element"/> class.
        /// </summary>
        public Element()
            : base("element")
        {
        }
    }

    /// <summary>
    /// Class representing the 'shadow' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Shadow : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Shadow"/> class.
        /// </summary>
        public Shadow()
            : base("shadow")
        {
        }
    }

    /// <summary>
    /// Class representing the 'slot' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Slot : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Slot"/> class.
        /// </summary>
        public Slot()
            : base("slot")
        {
        }
    }

    /// <summary>
    /// Class representing the 'template' html element.
    /// </summary>
    /// <seealso cref="HtmlElement" />
    public class Template : HtmlElement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Template"/> class.
        /// </summary>
        public Template()
            : base("template")
        {
        }
    }
}
